package com.awardselection.team.mapper;

import com.awardselection.team.dto.AwardsDTO;
import com.awardselection.team.model.Awards;
import com.awardselection.team.model.AwardsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AwardsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table awards
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    long countByExample(AwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table awards
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int deleteByExample(AwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table awards
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table awards
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int insert(Awards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table awards
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int insertSelective(Awards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table awards
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    List<Awards> selectByExample(AwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table awards
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    Awards selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table awards
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") Awards record, @Param("example") AwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table awards
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByExample(@Param("record") Awards record, @Param("example") AwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table awards
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByPrimaryKeySelective(Awards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table awards
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByPrimaryKey(Awards record);

    List<AwardsDTO> selectAllAwards();
}