package com.awardselection.team.mapper;

import com.awardselection.team.dto.DeclaresDTO;
import com.awardselection.team.model.Declares;
import com.awardselection.team.model.DeclaresExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeclaresMapper {

//    ------MY METHOD-----------
    List<DeclaresDTO> findDeclareByCid(Integer id);

//    ------MY METHOD-----------



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table declares
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    long countByExample(DeclaresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table declares
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int deleteByExample(DeclaresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table declares
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table declares
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int insert(Declares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table declares
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int insertSelective(Declares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table declares
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    List<Declares> selectByExample(DeclaresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table declares
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    Declares selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table declares
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") Declares record, @Param("example") DeclaresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table declares
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByExample(@Param("record") Declares record, @Param("example") DeclaresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table declares
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByPrimaryKeySelective(Declares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table declares
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByPrimaryKey(Declares record);
}