package com.awardselection.team.mapper;

import com.awardselection.team.model.Professor;
import com.awardselection.team.model.ProfessorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProfessorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professor
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    long countByExample(ProfessorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professor
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int deleteByExample(ProfessorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professor
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professor
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int insert(Professor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professor
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int insertSelective(Professor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professor
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    List<Professor> selectByExample(ProfessorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professor
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    Professor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professor
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") Professor record, @Param("example") ProfessorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professor
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByExample(@Param("record") Professor record, @Param("example") ProfessorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professor
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByPrimaryKeySelective(Professor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professor
     *
     * @mbg.generated Mon Jun 15 21:02:33 CST 2020
     */
    int updateByPrimaryKey(Professor record);
}